version: "2"
services:
    www:
        build: .
        ports: 
            - "8001:80"
        volumes:
            - ./www:/var/www/html/
        links:
            - db
        networks:
            - default
            - postgresql
        depends_on:
            - db
            - postgresql
    db:
        image: mysql:5.7.13 
        ports: 
            - "3306:3306"
        environment:
            MYSQL_DATABASE: myDb
            MYSQL_USER: user
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test
        volumes:
            - ./dump/m:/docker-entrypoint-initdb.d
            - persistent:/var/lib/mysql
        networks:
            - default
    phpmyadmin:
        image: phpmyadmin
        links: 
            - db:db
        ports:
            - 8000:80
        environment:
            MYSQL_USER: user
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test
    postgresql:
        image: postgres:13
        environment:
            POSTGRES_DB: myDb
            POSTGRES_USER: user
            POSTGRES_PASSWORD: test
        ports:
            - "5432:5432"
        volumes:
            - ./dump/p:/docker-entrypoint-initdb.d
            - postgres-data:/var/lib/postgresql/data
        networks:
            - default

volumes:
    persistent:
    postgres-data: